#**Array Creation**
There are several ways to create arrays.

For example, you can create an array from a regular **Python list or tuple** using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [ ]:
import numpy as np


In [ ]:
a = np.array([2,3,4])
print(a)
a.dtype

[2 3 4]


dtype('int64')

In [ ]:
b = np.array([1.2,3.5,5.1])
print(b)
b.dtype

[1.2 3.5 5.1]


dtype('float64')

array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.



In [ ]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
c = np.array( [ [1,2 + 3j], [3,4] ], dtype=complex ) #The type of the array can also be explicitly specified at creation time:
c

array([[1.+0.j, 2.+3.j],
       [3.+0.j, 4.+0.j]])

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.empty((2,3)) #unintialized

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
print(np.arange(10))  
print(np.arange(10,30,5)) #Last number(30) is not inclusive here
print(np.arange(0,2,0.3)) #accepts float arguments



[0 1 2 3 4 5 6 7 8 9]
[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [ ]:
np.linspace(0,2,9) #0 and 2 both are inclusive here
# 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

#**ATTRIBUTES OF ndarray**

**ndarray.ndim**
the number of axes (dimensions) of the array.

**ndarray.shape**
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

**ndarray.size**
the total number of elements of the array. This is equal to the product of the elements of shape.

**ndarray.dtype**
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

**ndarray.itemsize**
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

**ndarray.data**
the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [ ]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a.shape

(3, 5)

In [ ]:
a.ndim

2

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.size

15

In [ ]:
a.itemsize

In [ ]:
type(a)

In [ ]:
b = np.array([6, 7, 8])
print(b)
print(b.shape)
print(type(b))
b.dtype

#**Printing Arrays**

When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:


*   the last axis is printed from left to right,
*   the second-to-last is printed from top to bottom,
*   the rest are also printed from top to bottom, with each slice separated from the next by an empty line.


One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.


In [ ]:
a = np.arange(6)  
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
b = np.arange(12).reshape(4,3) #2d array
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
c = np.arange(24).reshape(2,3,4) #3d array
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
print(np.arange(10000))
print(np.arange(10000).reshape(100,100))



[   0    1    2 ... 9997 9998 9999]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


#**Basic Operations**

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [ ]:
a = np.array( [20,30,40,50] )
b =np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [ ]:
c = a-b #subtraction
c

array([20, 29, 38, 47])

In [ ]:
b**2  #square

array([ 0,  1,  8, 27])

In [ ]:
10*np.sin(a)  #multiplication and sin


array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [ ]:
a<35  #condition check

array([ True,  True, False, False])

In [ ]:
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
                [3,4]] )

A*B  # element wise product

array([[2, 0],
       [0, 4]])

In [ ]:
A @ B #matrix product

array([[5, 4],
       [3, 4]])

In [ ]:
A.dot(B)  #another matrix product same as above

array([[5, 4],
       [3, 4]])

In [ ]:
rg = np.random.default_rng(1)     # create instance of default random number generator
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))
a *= 3
a


array([[3, 3, 3],
       [3, 3, 3]])

In [ ]:
print(b)
b+=a
b

[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]


array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [ ]:
#a+=b  
## b is not automatically converted to integer type

In [ ]:
a = rg.random((2,3))
print(a)
print(a.sum())
print(a.min())
print(a.max())




[[0.82770259 0.40919914 0.54959369]
 [0.02755911 0.75351311 0.53814331]]
3.1057109529998157
0.027559113243068367
0.8277025938204418


In [ ]:
b = np.arange(12).reshape(3,4)
print(b)
print("--------------------------")
print(b.sum(axis =0))    # sum of each column
print("--------------------------")

print(b.sum(axis =1))    # sum of each row
print("--------------------------")
print(b.min(axis =1))    # min of each row
print("--------------------------")
print(b.cumsum(axis =1))    # cumulative sum along each row
print("--------------------------")



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------------
[12 15 18 21]
--------------------------
[ 6 22 38]
--------------------------
[0 4 8]
--------------------------
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]
--------------------------


#**Universal Functions**

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [ ]:
b = np.arange(3)
print(b)
print("--------------------------")
print(np.exp(b))
print("--------------------------")
print(np.sqrt(b))
print("--------------------------")
c = np.array([2.,-1.,4.])
print(np.add(b,c))



[0 1 2]
--------------------------
[1.         2.71828183 7.3890561 ]
--------------------------
[0.         1.         1.41421356]
--------------------------
[2. 0. 6.]


#**Indexing, Slicing and Iterating**



One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.



In [ ]:
a = np.arange(10)**3
print(a)
print("--------------------------")
print(a[2])
print("--------------------------")
print(a[2:5])
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000
print("--------------------------")
print(a)
print("--------------------------")
print(a[: : -1])       # reversed a
print("--------------------------")
print(a)
print("--------------------------")

for i in a:
  print(i**(1/3.))

[  0   1   8  27  64 125 216 343 512 729]
--------------------------
8
--------------------------
[ 8 27 64]
--------------------------
[1000    1 1000   27 1000  125  216  343  512  729]
--------------------------
[ 729  512  343  216  125 1000   27 1000    1 1000]
--------------------------
[1000    1 1000   27 1000  125  216  343  512  729]
--------------------------
9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas

In [ ]:
def f(x,y):
  return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [ ]:
print(b[2,3])
print("--------------------------")
print(b[0:5,1])   #each row in second column of b
print("--------------------------")
print(b[:,1])  #equivalent to the previous example
print("--------------------------")
print(b[1:3,:])     # each column in the second and third row of b
print("--------------------------")
print(b[-1])         # the last row. Equivalent to b[-1,:]
print("--------------------------")
for row in b:
     print(row)

23
--------------------------
[ 1 11 21 31 41]
--------------------------
[ 1 11 21 31 41]
--------------------------
[[10 11 12 13]
 [20 21 22 23]]
--------------------------
[40 41 42 43]
--------------------------
[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


#**Shape Manipulation**

In [ ]:
a = np.floor(10*rg.random((3,4)))
print(a)
print("--------------------------")
print(a.shape)
print("--------------------------")
print(a.ravel()) # returns the array, flattened
print("--------------------------")
print(a.reshape(6,2)) # returns the array with a modified shape

print("--------------------------")
print(a.T.shape) # returns the array, transposed

print("--------------------------")
print(a.shape)
# Note here that the shape of array is still (3,4)

[[3. 7. 3. 4.]
 [1. 4. 2. 2.]
 [7. 2. 4. 9.]]
--------------------------
(3, 4)
--------------------------
[3. 7. 3. 4. 1. 4. 2. 2. 7. 2. 4. 9.]
--------------------------
[[3. 7.]
 [3. 4.]
 [1. 4.]
 [2. 2.]
 [7. 2.]
 [4. 9.]]
--------------------------
(4, 3)
--------------------------
(3, 4)


In [ ]:
#The reshape function returns its argument with a modified shape,whereas the ndarray.resize method modifies the array itself:
a.resize(2,6)
a

array([[3., 7., 3., 4., 1., 4.],
       [2., 2., 7., 2., 4., 9.]])

In [ ]:
#If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
a.reshape(3,-1)

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

#**Copies and Views**
When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. This is often a source of confusion for beginners. There are three cases:



**No Copy at All**

Simple assignments make no copy of objects or their data.







In [ ]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
             [ 8,  9, 10, 11]])
b = a            # no new object is created
b is a           # a and b are two names for the same ndarray object



True

**View or Shallow Copy**

Different array objects can share the same data. The view method creates a new array object that looks at the same data.





In [ ]:
c = a.view()
c is a


False

In [ ]:
c.base is a  # c is a view of the data owned by a


True

In [ ]:
c.flags.owndata

False

In [ ]:
c = c.reshape((2, 6)) 
print(a)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
c[0, 4] = 1234    # a's data changes
a                  

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

Slicing an array returns a view of it:



In [ ]:
s = a[ : , 1:3] 
s[:] = 10        
# s[:] is a view of s. Note the difference between s = 10 and s[:] = 10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

**Deep Copy**

The copy method makes a complete copy of the array and its data.



In [ ]:
d = a.copy() # a new array object with new data is created
d is a

False

In [ ]:
d.base is a

False

In [ ]:
d[0,0] = 9999
print(a)
print(d)

[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]
[[9999   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]
